#!/bin/bash
# make-ppa-source.sh — Generate .orig.tar.gz for Launchpad PPA upload.
#
# Bundles fcitx5-skey source + skey-engine (Rust) into a single orig tarball
# that Launchpad buildd can build without internet access.
#
# Usage:
#   ./scripts/make-ppa-source.sh [version] [series]
#
# If version is omitted, it is extracted from CMakeLists.txt.
# If series is omitted, it is auto-detected from lsb_release.
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ── Resolve version ──────────────────────────────────────────────────────
if [ -n "$1" ]; then
    VERSION="$1"
else
    VERSION=$(grep -oP 'project\(fcitx5-skey VERSION \K[0-9.]+' CMakeLists.txt)
fi

# ── Resolve series ───────────────────────────────────────────────────────
if [ -n "$2" ]; then
    SERIES="$2"
else
    SERIES=$(lsb_release -cs 2>/dev/null || echo "resolute")
fi

if [ -z "$VERSION" ]; then
    echo "Error: could not determine version from CMakeLists.txt" >&2
    exit 1
fi

ENGINE_VERSION=$(grep -oP 'set\(SKEY_ENGINE_VERSION "\K[^"]+' CMakeLists.txt)
PKG_NAME="fcitx5-skey"
TARBALL="${PKG_NAME}_${VERSION}.orig.tar.gz"
WORKDIR="$(mktemp -d)"
STAGING="${WORKDIR}/${PKG_NAME}-${VERSION}"

echo "=== Creating orig tarball for ${PKG_NAME} v${VERSION} ==="
echo "  Engine version: ${ENGINE_VERSION}"
echo "  Output: ../${TARBALL}"

# ── Cleanup trap ─────────────────────────────────────────────────────────
cleanup() { rm -rf "$WORKDIR"; }
trap cleanup EXIT

# ── Copy project source (exclude build artifacts and CI) ─────────────────
mkdir -p "$STAGING"

echo "→ Copying project source (without debian/ — packaging goes in .debian.tar.xz)..."
rsync -a \
    --exclude='.git' \
    --exclude='.venv/' \
    --exclude='.env/' \
    --exclude='.cache/' \
    --exclude='__pycache__/' \
    --exclude='*.pyc' \
    --exclude='build/' \
    --exclude='build-deb/' \
    --exclude='build-ppa/' \
    --exclude='*.deb' \
    --exclude='*.rpm' \
    --exclude='*.pkg.tar.zst' \
    --exclude='*.sig' \
    --exclude='.github/' \
    --exclude='.claude/' \
    --exclude='CLAUDE.md' \
    --exclude='AGENTS.md' \
    --exclude='node_modules/' \
    --exclude='debian/' \
    ./ "$STAGING/"

# ── Clone skey-engine into the staging tree ──────────────────────────────
echo "→ Cloning skey-engine ${ENGINE_VERSION}..."
git clone --branch "${ENGINE_VERSION}" --depth 1 \
    https://github.com/collyn/skey-engine.git \
    "${STAGING}/skey-engine"

# Remove engine's .git so it doesn't confuse dpkg-source.
# Also remove Cargo.lock — the bundled lock may use format v4 (requires
# Rust ≥ 1.78). It will be regenerated by cargo during build.
rm -rf "${STAGING}/skey-engine/.git" "${STAGING}/skey-engine/Cargo.lock"

# ── Rust 1.75 compatibility (Launchpad buildd toolchain) ─────────────────
# skey-engine (edition 2021) uses #[unsafe(no_mangle)] which requires Rust
# >= 1.82; the buildd ships Rust 1.75. Rewrite to the old #[no_mangle]
# syntax, which both toolchains accept. Replaces the static quilt patch
# debian/patches/fix-rust-175-compat.patch — no per-tag patch refresh needed.
echo "→ Rewriting #[unsafe(no_mangle)] for Rust 1.75 buildd..."
find "${STAGING}/skey-engine/src" -name '*.rs' -exec sed -i \
    's/#\[unsafe(no_mangle)\]/#[no_mangle]/g' {} +
if grep -rq 'unsafe(no_mangle)' "${STAGING}/skey-engine/src"; then
    echo "Error: #[unsafe(no_mangle)] remains after rewrite — check the sed pattern" >&2
    exit 1
fi

# ── Vendor Cargo dependencies for offline build ─────────────────────────
echo "→ Vendoring Cargo dependencies..."
pushd "${STAGING}/skey-engine" > /dev/null
cargo vendor > /dev/null 2>&1 || {
    echo "Warning: cargo vendor failed, continuing without vendored deps" >&2
}
if [ -d vendor ]; then
    mkdir -p .cargo
    cat > .cargo/config.toml << 'CARGO_EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
CARGO_EOF
    # Remove non-essential files from vendor dir that lintian complains about
    find vendor -name '*.html' -delete 2>/dev/null || true
    find vendor -name '.github' -type d -exec rm -rf {} + 2>/dev/null || true
    find vendor -name '.gitignore' -delete 2>/dev/null || true
    echo "   Vendored $(find vendor -name '*.crate' 2>/dev/null | wc -l) crates"
fi
popd > /dev/null

# ── Create the orig tarball ──────────────────────────────────────────────
# Deterministic tar + gzip (sorted entries, zeroed mtimes, no gzip header
# timestamp) so rebuilding the same version produces bit-identical tarballs.
# Launchpad rejects same-name files with different contents — even after the
# package is deleted from the PPA — so reproducibility keeps re-uploads possible.
echo "→ Creating ${TARBALL}..."
tar --sort=name --mtime='@0' --owner=0 --group=0 --numeric-owner \
    -cf - -C "$WORKDIR" "${PKG_NAME}-${VERSION}" | \
    gzip -n > "${REPO_ROOT}/../${TARBALL}"

echo ""
echo "=== Done ==="
echo "  Orig tarball: $(readlink -f "${REPO_ROOT}/../${TARBALL}")"
echo ""
echo "Next steps:"
echo "  1. cd $(readlink -f "${REPO_ROOT}")"
echo "  2. debuild -S -sa"
echo "  3. lintian --pedantic ../${PKG_NAME}_${VERSION}-*_source.changes"
echo "  4. dput ppa:collyn094/${PKG_NAME} ../${PKG_NAME}_${VERSION}-*_source.changes"
