#!/bin/bash
# make-ppa-source.sh — Generate .orig.tar.gz for Launchpad PPA upload.
#
# Bundles fcitx5-skey source + skey-engine (Rust) into a single orig tarball
# that Launchpad buildd can build without internet access.
#
# Usage:
#   ./scripts/make-ppa-source.sh [version]
#
# If version is omitted, it is extracted from CMakeLists.txt.
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ── Resolve version ──────────────────────────────────────────────────────
if [ -n "$1" ]; then
    VERSION="$1"
else
    VERSION=$(grep -oP 'project\(fcitx5-skey VERSION \K[0-9.]+' CMakeLists.txt)
fi

if [ -z "$VERSION" ]; then
    echo "Error: could not determine version from CMakeLists.txt" >&2
    exit 1
fi

ENGINE_VERSION=$(grep -oP 'set\(SKEY_ENGINE_VERSION "\K[^"]+' CMakeLists.txt)
PKG_NAME="fcitx5-skey"
TARBALL="${PKG_NAME}_${VERSION}.orig.tar.gz"
WORKDIR="$(mktemp -d)"
STAGING="${WORKDIR}/${PKG_NAME}-${VERSION}"

echo "=== Creating orig tarball for ${PKG_NAME} v${VERSION} ==="
echo "  Engine version: ${ENGINE_VERSION}"
echo "  Output: ../${TARBALL}"

# ── Cleanup trap ─────────────────────────────────────────────────────────
cleanup() { rm -rf "$WORKDIR"; }
trap cleanup EXIT

# ── Copy project source (exclude build artifacts and CI) ─────────────────
mkdir -p "$STAGING"

echo "→ Copying project source..."
rsync -a \
    --exclude='.git' \
    --exclude='.venv/' \
    --exclude='.env/' \
    --exclude='.cache/' \
    --exclude='__pycache__/' \
    --exclude='*.pyc' \
    --exclude='build/' \
    --exclude='build-deb/' \
    --exclude='build-ppa/' \
    --exclude='*.deb' \
    --exclude='*.rpm' \
    --exclude='*.pkg.tar.zst' \
    --exclude='*.sig' \
    --exclude='.github/' \
    --exclude='.claude/' \
    --exclude='CLAUDE.md' \
    --exclude='AGENTS.md' \
    --exclude='node_modules/' \
    ./ "$STAGING/"

# ── Clone skey-engine into the staging tree ──────────────────────────────
echo "→ Cloning skey-engine ${ENGINE_VERSION}..."
git clone --branch "${ENGINE_VERSION}" --depth 1 \
    https://github.com/collyn/skey-engine.git \
    "${STAGING}/skey-engine"

# Remove engine's .git so it doesn't confuse dpkg-source.
# Also remove Cargo.lock — the bundled lock may use format v4 (requires
# Rust ≥ 1.78). It will be regenerated by cargo during build.
rm -rf "${STAGING}/skey-engine/.git" "${STAGING}/skey-engine/Cargo.lock"

# ── Vendor Cargo dependencies for offline build ─────────────────────────
echo "→ Vendoring Cargo dependencies..."
pushd "${STAGING}/skey-engine" > /dev/null
cargo vendor > /dev/null 2>&1 || {
    echo "Warning: cargo vendor failed, continuing without vendored deps" >&2
}
if [ -d vendor ]; then
    mkdir -p .cargo
    cat > .cargo/config.toml << 'CARGO_EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
CARGO_EOF
    echo "   Vendored $(find vendor -name '*.crate' 2>/dev/null | wc -l) crates"
fi
popd > /dev/null

# ── Auto-generate debian/changelog ──────────────────────────────────────
echo "→ Generating debian/changelog..."
SERIES=$(lsb_release -cs 2>/dev/null || echo "resolute")
if [ -f "debian/changelog" ]; then
    # Update existing changelog with new version
    dch --newversion "${VERSION}-1" \
        --distribution "${SERIES}" \
        --urgency medium \
        "Release ${VERSION} with skey-engine ${ENGINE_VERSION}." \
        2>/dev/null || {
        # Fallback: write minimal changelog
        cat > "${STAGING}/debian/changelog" << DCH_EOF
${PKG_NAME} (${VERSION}-1) ${SERIES}; urgency=medium

  * Release ${VERSION} with skey-engine ${ENGINE_VERSION}.

 -- Nguyen Tien Huy <collyn094@gmail.com>  $(date -R)
DCH_EOF
    }
else
    # Create new changelog
    cat > "${STAGING}/debian/changelog" << DCH_EOF
${PKG_NAME} (${VERSION}-1) ${SERIES}; urgency=medium

  * Release ${VERSION} with skey-engine ${ENGINE_VERSION}.

 -- Nguyen Tien Huy <collyn094@gmail.com>  $(date -R)
DCH_EOF
fi

# ── Create the orig tarball ──────────────────────────────────────────────
echo "→ Creating ${TARBALL}..."
tar czf "${REPO_ROOT}/../${TARBALL}" -C "$WORKDIR" "${PKG_NAME}-${VERSION}"

echo ""
echo "=== Done ==="
echo "  Orig tarball: $(readlink -f "${REPO_ROOT}/../${TARBALL}")"
echo ""
echo "Next steps:"
echo "  1. cd $(readlink -f "${REPO_ROOT}")"
echo "  2. debuild -S -sa"
echo "  3. lintian --pedantic ../${PKG_NAME}_${VERSION}-*_source.changes"
echo "  4. dput ppa:collyn094/${PKG_NAME} ../${PKG_NAME}_${VERSION}-*_source.changes"
